name: Terraform CI

on:
  push:
    branches:
      - main
      - my-branch
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_REGION: us-east-1

    defaults:
      run:
        working-directory: modules/tf-module-example

    permissions:
      id-token: write   # required for OIDC
      contents: read    # required to checkout the repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761763536:role/GithubActionsRole
          role-session-name: github-actions-dev
          aws-region: ${{ env.TF_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false -no-color
